<?php

return [
    // Assumption: usage XLSX for jneibb is generated externally in this directory.
    'jneibb_usage_base_path' => env('JNEIBB_USAGE_BASE_PATH', '/var/www/api.skyware.systems/storage/app/client_usage'),

    // Assumption: invoice line details are generated by internal billing logic and stored in invoice_details.
    'default_item_description' => env('BILLING_DEFAULT_ITEM_DESCRIPTION', 'Monthly service billing'),

    // Assumption: meterai is required when subtotal (before tax) is >= 5,000,000 IDR.
    'meterai_threshold' => env('BILLING_METERAI_THRESHOLD', 5000000),
];
